#!/usr/local/bin/node
/*cfl-simple script for listing functions in C source code.
pipe the source code into this script and it'll list function names
with their descriptions(if they're provided; only C89 comments are
suppoerted).
if you desire to get more details(function return type and parameter list)
-specify a "v"(verbose) argument so entire command will be: <src text>|cfl v.
this script doesn't use a complicated parse algorithm, it merely uses
regular expressions(which actually is right a complicated stuff!) so it
won't work in tricky cases. but you just don't use them and everything is
going to be fine(it anyway is) :)*/
var fs=require("fs");
var inp=fs.readFileSync(0).toString();/*read stdin*/
/*main regex for extracting function declarations from source text.*/
var reg=/\n([\w_\*]+)(\n| )+([\w_]+)[\s\t\n]*(\([^\)]*?\))(\/\*(.*?)\*\/)?((\s?|\n){((\/\*(.*?)\*\/)?))/gms;
var m;/*variable for storing regex match.*/
var iv=process.argv[2]=="v";/*is verbose.*/
var r="";/*resulting string.*/
var fm=1;/*is first match.*/
while(m=reg.exec(inp)){/*iterate over function declaration matches.*/
/*pre-comment,return type,function name,parameter list,
post-comment,(nam()<com.>\n{)
post-post comment(nam(){<com.>\n).*/
var{1:ret,3:nam,4:par,6:pocm,11:ppcm}=m;
/*look for pre-comment separately 'cause it's much easier
than trying to build up a proper regex for this purpose.*/
var prcm=undefined;
if(inp.slice(0,m.index).endsWith("*/")){
prcm=inp.slice(inp.slice(0,m.index).lastIndexOf("/*")+2,m.index-2)
}
/*match line index(starts from 0,but we'll print it starting from 1).*/
var li=inp.slice(0,m.index).split("\n").length;
/*start building up a resulting string.
and do not forget about verbose flag.*/
if(!fm)r+="\n";
r+=`${li+1}: `
if(iv)r+=`${ret} `;
/*build strings for function description comments.*/
var prcms=prcm?`${prcm}${pocm||ppcm?";":""}`:""
var pocms=pocm?`${pocm}${ppcm?";":""}`:"";
var ppcms=ppcm?ppcm:"";
r+=nam;
if(iv)r+=par;
r+=`${prcms||pocms||ppcms?"-":""}${prcms}${pocms}${ppcms}\n`;
fm=0;/*it's not a first match anymore.*/
}
process.stdout.write(r);/*write result to stdout.*/
return 0;/*exit program.*/